// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBackendStatus():Promise<main.BackendStatus>;

export function OpenExternal(arg1:string):Promise<void>;

export function PickOPMLFile():Promise<string>;

export function RefreshWindowSettings():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveConfigFile(arg1:string):Promise<string>;

export function SaveDatabaseFile():Promise<string>;

export function SaveOPMLFile():Promise<string>;

export function SavePNGFile(arg1:string):Promise<string>;

export function ShouldPreventClose():Promise<boolean>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WindowUnmaximise():Promise<void>;
