// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApiRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApiRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetAPIToken() {
  return window['go']['main']['App']['GetAPIToken']();
}

export function GetBackendStatus() {
  return window['go']['main']['App']['GetBackendStatus']();
}

export function GetCachedUpdate() {
  return window['go']['main']['App']['GetCachedUpdate']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetUpdateProgress() {
  return window['go']['main']['App']['GetUpdateProgress']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function LoadWindowState() {
  return window['go']['main']['App']['LoadWindowState']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PickOPMLFile() {
  return window['go']['main']['App']['PickOPMLFile']();
}

export function RefreshWindowSettings() {
  return window['go']['main']['App']['RefreshWindowSettings']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveBackupFile(arg1) {
  return window['go']['main']['App']['SaveBackupFile'](arg1);
}

export function SaveConfigFile(arg1) {
  return window['go']['main']['App']['SaveConfigFile'](arg1);
}

export function SaveDatabaseFile() {
  return window['go']['main']['App']['SaveDatabaseFile']();
}

export function SaveOPMLFile() {
  return window['go']['main']['App']['SaveOPMLFile']();
}

export function SavePNGFile(arg1) {
  return window['go']['main']['App']['SavePNGFile'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function ShouldPreventClose() {
  return window['go']['main']['App']['ShouldPreventClose']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
