// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function GetAPIToken():Promise<string>;

export function GetBackendStatus():Promise<main.BackendStatus>;

export function GetVersion():Promise<string>;

export function GetWindowState():Promise<main.WindowState>;

export function LoadWindowState():Promise<main.WindowState>;

export function OpenExternal(arg1:string):Promise<void>;

export function PickOPMLFile():Promise<string>;

export function RefreshWindowSettings():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveBackupFile(arg1:string):Promise<string>;

export function SaveConfigFile(arg1:string):Promise<string>;

export function SaveDatabaseFile():Promise<string>;

export function SaveOPMLFile():Promise<string>;

export function SavePNGFile(arg1:string):Promise<string>;

export function SaveWindowState(arg1:boolean):Promise<void>;

export function ShouldPreventClose():Promise<boolean>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartUpdate():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WindowUnmaximise():Promise<void>;
